Active_gNBs = ( "gNB-CU-Donor" );
Asn1_verbosity = "none";

gNBs =
(
 {
    ////////// Identification parameters:
    gNB_ID    = 0xe00;
    gNB_name  = "gNB-CU-Donor";

    // Tracking area code
    tracking_area_code  =  1;

    plmn_list = ({ mcc = 208; mnc = 99; mnc_length = 2; snssaiList = ({ sst = 1; }) });

    # F1 介面設定
    tr_s_preference = "f1";
    # local_s_if_name = "enxc84d44350030"; # [修改] 改為實體網卡名稱
    local_s_address = "192.168.88.1";    # [修改] 改為實體 IP
    remote_s_address = "0.0.0.0";
    local_s_portc   = 38472;
    local_s_portd   = 2153;  # F1-U Port
    remote_s_portc  = 2152;
    remote_s_portd  = 2152;

    # SCTP definitions
    SCTP :
    {
        SCTP_INSTREAMS  = 2;
        SCTP_OUTSTREAMS = 2;
    };

    ////////// AMF parameters:
    amf_ip_address = ({ ipv4 = "192.168.88.132"; });

    NETWORK_INTERFACES :
    {
        # 北向 (NG) - CU 宣告自己的身分 IP
        # GNB_INTERFACE_NAME_FOR_NG_AMF              = "enxc84d44350030"; # [修改] 實體網卡
        GNB_IPV4_ADDRESS_FOR_NG_AMF                = "192.168.88.1";    # [修改] 實體 IP
        # GNB_INTERFACE_NAME_FOR_NGU                 = "enxc84d44350030"; # [修改] 實體網卡
        GNB_IPV4_ADDRESS_FOR_NGU                   = "192.168.88.1";    # [修改] 實體 IP
        GNB_PORT_FOR_S1U                           = 2152;

        # 南向 F1 介面
        GNB_IPV4_ADDRESS_FOR_F1C                   = "192.168.88.1";    # [修改] 實體 IP
        GNB_PORT_FOR_F1C                           = 38472;
        GNB_IPV4_ADDRESS_FOR_F1U                   = "192.168.88.1";    # [修改] 實體 IP
        GNB_PORT_FOR_F1U                           = 2153;
    };
  }
);

security = {
  ciphering_algorithms = ( "nea0" );
  integrity_algorithms = ( "nia2", "nia0" );
  drb_ciphering        = "yes";
  drb_integrity        = "no";
};

log_config : {
  global_log_level                      ="info"; # reduce cpu loading
  f1ap_log_level                        ="info";
  ngap_log_level                        ="info";
};