Active_gNBs = ( "gNB-CU-Donor" );
Asn1_verbosity = "none";

gNBs =
(
 {
    ////////// Identification parameters:
    gNB_ID    = 0xe00;
    gNB_name  = "gNB-CU-Donor";

    // Tracking area code
    tracking_area_code  =  1;

    plmn_list = ({ mcc = 208; mnc = 99; mnc_length = 2; snssaiList = ({ sst = 1; }) });

    # F1 介面設定
    tr_s_preference = "f1";
    local_s_if_name = "eth0";
    local_s_address = "192.168.71.140";
    remote_s_address = "0.0.0.0";
    local_s_portc   = 38472;
    local_s_portd   = 2153;  # F1-U Port
    remote_s_portc  = 2152;
    remote_s_portd  = 2152;

    # SCTP definitions
    SCTP :
    {
        SCTP_INSTREAMS  = 2;
        SCTP_OUTSTREAMS = 2;
    };

    ////////// AMF parameters:
    amf_ip_address = ({ ipv4 = "192.168.71.132"; });

    NETWORK_INTERFACES :
    {
        # 北向 (NG)
        GNB_IPV4_ADDRESS_FOR_NG_AMF              = "192.168.71.140";
        GNB_IPV4_ADDRESS_FOR_NGU                 = "192.168.71.140";
        GNB_PORT_FOR_S1U                         = 2152;

        # 南向 (F1)
        GNB_IPV4_ADDRESS_FOR_F1C                 = "192.168.71.140";
        GNB_PORT_FOR_F1C                         = 38472;
        GNB_IPV4_ADDRESS_FOR_F1U                 = "192.168.71.140";
        GNB_PORT_FOR_F1U                         = 2153; # 確保與上面 local_s_portd 一致
    };
  }
);

security = {
  ciphering_algorithms = ( "nea0" );
  integrity_algorithms = ( "nia2", "nia0" );
  drb_ciphering        = "yes";
  drb_integrity        = "no";
};

log_config : {
  global_log_level                      ="error"; # reduce cpu loading
  f1ap_log_level                        ="error";
  ngap_log_level                        ="error";
};