version: '3.8'

services:
    # ==========================================
    # Group A: 連接 Node 3 (Port 4046)
    # ==========================================
    rfsim5g-end-ue-1:
        # build: { context: ., dockerfile: Dockerfile.ue }
        image: oaisoftwarealliance/oai-nr-ue:develop
        container_name: rfsim5g-end-ue-1
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # 這裡改成 PC 1 實體 IP，Port 改為 4046
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001111 --rfsimulator.serveraddr 192.168.88.1 --rfsimulator.serverport 4046 --log_config.global_log_options level,nocolor,time

    rfsim5g-end-ue-2:
        # build: { context: ., dockerfile: Dockerfile.ue }
        image: oaisoftwarealliance/oai-nr-ue:develop
        container_name: rfsim5g-end-ue-2
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # 這裡改成 PC 1 實體 IP，Port 改為 4046
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001112 --rfsimulator.serveraddr 192.168.88.1 --rfsimulator.serverport 4046 --log_config.global_log_options level,nocolor,time

    # ==========================================
    # Group B: 連接 Node 4 (Port 4047)
    # ==========================================
    rfsim5g-end-ue-3:
        # build: { context: ., dockerfile: Dockerfile.ue }
        image: oaisoftwarealliance/oai-nr-ue:develop
        container_name: rfsim5g-end-ue-3
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # Port 改為 4047
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001113 --rfsimulator.serveraddr 192.168.88.1 --rfsimulator.serverport 4047 --log_config.global_log_options level,nocolor,time

    rfsim5g-end-ue-4:
        # build: { context: ., dockerfile: Dockerfile.ue }
        image: oaisoftwarealliance/oai-nr-ue:develop
        container_name: rfsim5g-end-ue-4
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # Port 改為 4047
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001114 --rfsimulator.serveraddr 192.168.88.1 --rfsimulator.serverport 4047 --log_config.global_log_options level,nocolor,time

    # ==========================================
    # Group C: 連接 Node 5 (Port 4048)
    # ==========================================
    rfsim5g-end-ue-5:
        # build: { context: ., dockerfile: Dockerfile.ue }
        image: oaisoftwarealliance/oai-nr-ue:develop
        container_name: rfsim5g-end-ue-5
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # Port 改為 4048
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001115 --rfsimulator.serveraddr 192.168.88.1 --rfsimulator.serverport 4048 --log_config.global_log_options level,nocolor,time

    rfsim5g-end-ue-6:
        # build: { context: ., dockerfile: Dockerfile.ue }
        image: oaisoftwarealliance/oai-nr-ue:develop
        container_name: rfsim5g-end-ue-6
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # Port 改為 4048
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001116 --rfsimulator.serveraddr 192.168.88.1 --rfsimulator.serverport 4048 --log_config.global_log_options level,nocolor,time

networks:
    default:
        driver: bridge