version: '3.8'

services:
    # ==========================================
    # Group A: Attached to IAB Node 3 (Left Leaf)
    # Target IP: 192.168.71.154
    # Target Port: 4046
    # ==========================================
    rfsim5g-end-ue-1:
        build: { context: ., dockerfile: Dockerfile.ue }
        container_name: rfsim5g-end-ue-1
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # IMSI: ...1111
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001111 --rfsimulator.serveraddr 192.168.71.154 --rfsimulator.serverport 4046 --log_config.global_log_options level,nocolor,time

    rfsim5g-end-ue-2:
        build: { context: ., dockerfile: Dockerfile.ue }
        container_name: rfsim5g-end-ue-2
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # IMSI: ...1112
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001112 --rfsimulator.serveraddr 192.168.71.154 --rfsimulator.serverport 4046 --log_config.global_log_options level,nocolor,time

    # ==========================================
    # Group B: Attached to IAB Node 4 (Middle)
    # Target IP: 192.168.71.156
    # Target Port: 4047
    # ==========================================
    rfsim5g-end-ue-3:
        build: { context: ., dockerfile: Dockerfile.ue }
        container_name: rfsim5g-end-ue-3
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # IMSI: ...1113
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001113 --rfsimulator.serveraddr 192.168.71.156 --rfsimulator.serverport 4047 --log_config.global_log_options level,nocolor,time

    rfsim5g-end-ue-4:
        build: { context: ., dockerfile: Dockerfile.ue }
        container_name: rfsim5g-end-ue-4
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # IMSI: ...1114
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001114 --rfsimulator.serveraddr 192.168.71.156 --rfsimulator.serverport 4047 --log_config.global_log_options level,nocolor,time

    # ==========================================
    # Group C: Attached to IAB Node 5 (Right Leaf)
    # Target IP: 192.168.71.158
    # Target Port: 4048
    # ==========================================
    rfsim5g-end-ue-5:
        build: { context: ., dockerfile: Dockerfile.ue }
        container_name: rfsim5g-end-ue-5
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # IMSI: ...1115
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001115 --rfsimulator.serveraddr 192.168.71.158 --rfsimulator.serverport 4048 --log_config.global_log_options level,nocolor,time

    rfsim5g-end-ue-6:
        build: { context: ., dockerfile: Dockerfile.ue }
        container_name: rfsim5g-end-ue-6
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        devices:
             - /dev/net/tun:/dev/net/tun
        environment:
            # IMSI: ...1116
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001116 --rfsimulator.serveraddr 192.168.71.158 --rfsimulator.serverport 4048 --log_config.global_log_options level,nocolor,time

networks:
    default:
        driver: bridge