version: '3.8'

services:
    # 0. O-RAN Near-RT RIC & xApps
    oai-flexric:
        image: oaisoftwarealliance/oai-flexric:develop
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        container_name: flexric
        networks:
            public_net:
                ipv4_address: 192.168.71.141
        volumes:
            - ./conf/flexric.conf:/usr/local/etc/flexric/flexric.conf
        healthcheck:
            test: /bin/bash -c "pgrep nearRT-RIC"
            interval: 10s
            timeout: 5s

    xapp-kpm-moni:
        image: oaisoftwarealliance/oai-flexric:develop
        command: "stdbuf -o0 /usr/local/flexric/xApp/c/monitor/xapp_kpm_moni"
        container_name: xapp-kpm-moni
        privileged: true
        cap_add: [NET_ADMIN]
        depends_on: [oai-flexric]
        networks:
            public_net:
                ipv4_address: 192.168.71.142
        environment:
            - NEAR_RT_RIC_IP=192.168.71.141
        volumes:
            - ./conf/flexric.conf:/usr/local/etc/flexric/flexric.conf

    xapp-gtp-moni:
        image: oaisoftwarealliance/oai-flexric:develop
        command: "stdbuf -o0 /usr/local/flexric/xApp/c/monitor/xapp_gtp_mac_rlc_pdcp_moni"
        container_name: xapp-gtp-moni
        depends_on: [oai-flexric]
        networks:
            public_net:
                ipv4_address: 192.168.71.143
        volumes:
            - ./conf/flexric.conf:/usr/local/etc/flexric/flexric.conf

    # 1. 5G Core Network
    mysql:
        container_name: "rfsim5g-mysql"
        image: mysql:8.0
        init: true
        volumes:
            - ./oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.71.131

    oai-amf:
        container_name: "rfsim5g-oai-amf"
        image: oaisoftwarealliance/oai-amf:v2.1.10
        environment:
            - TZ=Europe/paris
        volumes:
            - ./mini_nonrf_config.yaml:/openair-amf/etc/config.yaml
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.71.132

    oai-smf:
        container_name: "rfsim5g-oai-smf"
        image: oaisoftwarealliance/oai-smf:v2.1.10
        environment:
            - TZ=Europe/Paris
        volumes:
            - ./mini_nonrf_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai-amf
        networks:
            public_net:
                ipv4_address: 192.168.71.133

    oai-upf:
        container_name: "rfsim5g-oai-upf"
        image: oaisoftwarealliance/oai-upf:v2.1.10
        init: true
        environment:
            - TZ=Europe/Paris
        volumes:
            - ./mini_nonrf_config.yaml:/openair-upf/etc/config.yaml
        depends_on:
            - oai-smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.71.134
                interface_name: eth0
            traffic_net:
                ipv4_address: 192.168.72.134
                interface_name: eth1

    oai-ext-dn:
        privileged: true
        container_name: rfsim5g-oai-ext-dn
        image: oaisoftwarealliance/trf-gen-cn5g:focal
        init: true
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.0/24 via 192.168.72.134 dev eth0; sleep infinity"
        depends_on:
            - oai-upf
        networks:
            traffic_net:
                ipv4_address: 192.168.72.135
        healthcheck:
            test: /bin/bash -c "ping -c 2 192.168.72.134"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 5

    # 2. IAB Donor (CU + DU)
    rfsim5g-donor-cu:
        image: oaisoftwarealliance/oai-gnb:develop
        container_name: rfsim5g-donor-cu
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        environment:
            USE_ADDITIONAL_OPTIONS: --log_config.global_log_options level,nocolor,time
        depends_on: [oai-flexric, oai-upf]
        networks:
            public_net:
                ipv4_address: 192.168.71.140
        volumes:
            - ./conf/donor_cu.conf:/opt/oai-gnb/etc/gnb.conf
            - ./conf/flexric.conf:/opt/oai-gnb/etc/flexric.conf

    rfsim5g-donor-du:
        image: oaisoftwarealliance/oai-gnb:develop
        container_name: rfsim5g-donor-du
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        environment:
            USE_ADDITIONAL_OPTIONS: --rfsim --log_config.global_log_options level,nocolor,time
        depends_on: [rfsim5g-donor-cu]
        networks:
            public_net:
                ipv4_address: 192.168.71.144
        volumes:
            - ./conf/donor_du.conf:/opt/oai-gnb/etc/gnb.conf

    # 3. IAB Node 1 (Relay Node)
    rfsim5g-iab-mt:
        # image: oaisoftwarealliance/oai-nr-ue:develop
        build:
            context: .
            dockerfile: Dockerfile.ue

        container_name: rfsim5g-iab-mt
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        depends_on: [rfsim5g-donor-du]
        networks:
            public_net:
                ipv4_address: 192.168.71.150
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
             - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf  
        environment:
            # IAB 1 始終直連 Donor (.144)
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001100 --rfsimulator.serveraddr 192.168.71.144 --log_config.global_log_options level,nocolor,time

    rfsim5g-iab-du:
        image: oaisoftwarealliance/oai-gnb:develop
        container_name: rfsim5g-iab-du
        privileged: true
        depends_on: [rfsim5g-iab-mt]
        network_mode: "service:rfsim5g-iab-mt"
        volumes:
            - ./conf/iab_du.conf:/opt/oai-gnb/etc/gnb.conf
        environment:
            # Port 4044 
            USE_ADDITIONAL_OPTIONS: --rfsim --rfsimulator.serverport 4044 --log_config.global_log_options level,nocolor,time

    # 4. IAB Node 2 (Access Node)
    rfsim5g-iab-mt-2:
        # image: oaisoftwarealliance/oai-nr-ue:develop
        build:
            context: .
            dockerfile: Dockerfile.ue
        container_name: rfsim5g-iab-mt-2
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        # 這裡不寫死 depends_on IAB-1，因為它可能直連 Donor
        networks:
            public_net:
                ipv4_address: 192.168.71.152 # 新 IP
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
             - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf  
        environment:
            # IMSI 改為 ...1102 (避免衝突)
            # !!三角拓撲切換關鍵
            # mode A (直連 Donor - Link B): serveraddr 192.168.71.144
            # mode B (走 Relay - Link C): serveraddr 192.168.71.150
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001102 --rfsimulator.serveraddr 192.168.71.144 --log_config.global_log_options level,nocolor,time

    rfsim5g-iab-du-2:
        image: oaisoftwarealliance/oai-gnb:develop
        container_name: rfsim5g-iab-du-2
        privileged: true
        depends_on: [rfsim5g-iab-mt-2]
        network_mode: "service:rfsim5g-iab-mt-2" # 寄生在 MT-2
        volumes:
            - ./conf/iab_du_2.conf:/opt/oai-gnb/etc/gnb.conf
        environment:
            # Port 改為 4045 (給 End-UE 連)
            USE_ADDITIONAL_OPTIONS: --rfsim --rfsimulator.serverport 4045 --log_config.global_log_options level,nocolor,time

    # 5. End UE (接在 Node 2 下面)
    rfsim5g-end-ue:
        # image: oaisoftwarealliance/oai-nr-ue:develop
        build:
            context: .
            dockerfile: Dockerfile.ue

        container_name: rfsim5g-end-ue
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf  
        environment:
            # IMSI ...1103
            # serveraddr: 指向 IAB Node 2 (192.168.71.152)
            # serverport: 指向 4045
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001103 --rfsimulator.serveraddr 192.168.71.152 --rfsimulator.serverport 4045 --log_config.global_log_options level,nocolor,time
        depends_on: [rfsim5g-iab-du-2]
        networks:
            public_net:
                ipv4_address: 192.168.71.160
        devices:
             - /dev/net/tun:/dev/net/tun
    
    # UE 2 (連接 Node 2)
    rfsim5g-end-ue-2:
        # image: oaisoftwarealliance/oai-nr-ue:develop
        build:
            context: .
            dockerfile: Dockerfile.ue

        container_name: rfsim5g-end-ue-2
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        environment:
            # IMSI: ...1104
            # serverport: 4045 (連 IAB-Node-2)
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001104 --rfsimulator.serveraddr 192.168.71.152 --rfsimulator.serverport 4045 --log_config.global_log_options level,nocolor,time
        depends_on: [rfsim5g-iab-du-2]
        networks:
            public_net:
                ipv4_address: 192.168.71.161 # 新 IP

    # UE 3 (連接 Node 1 - 讓兩邊都有負載)
    rfsim5g-end-ue-3:
        # image: oaisoftwarealliance/oai-nr-ue:develop
        build:
            context: .
            dockerfile: Dockerfile.ue

        container_name: rfsim5g-end-ue-3
        privileged: true
        cap_add: [NET_ADMIN, NET_RAW]
        volumes:
            - ./conf/nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        environment:
            # IMSI: ...1105
            # serverport: 4044 (連 IAB-Node-1)
            # serveraddr: 192.168.71.150 (Node 1 IP)
            USE_ADDITIONAL_OPTIONS: --rfsim -r 106 --numerology 1 -C 3319680000 --ssb 516 --uicc0.imsi 208990100001105 --rfsimulator.serveraddr 192.168.71.150 --rfsimulator.serverport 4044 --log_config.global_log_options level,nocolor,time
        depends_on: [rfsim5g-iab-du]
        networks:
            public_net:
                ipv4_address: 192.168.71.162 # 新 IP

networks:
    public_net:
        driver: bridge
        name: rfsim5g-oai-public-net
        ipam:
            config:
                - subnet: 192.168.71.128/26
    traffic_net:
        driver: bridge
        name: rfsim5g-oai-traffic-net
        ipam:
            config:
                - subnet: 192.168.72.128/26